### ISSUE TITLE
Cannot save template file '../templates/default/cache/index.tpl.it' docker-compose

### ISSUE THREAD

**Issue by Asdespadas** [sgcommander/sgcommander#4]
Buenas,
Por una parte muchas gracias por subir este juego, le tengo mucha nostalgia y me gustaría ayudar lo que pudiera, aunque solo soy un administrador de sistemas Linux.

He seguido la guía para instalar con docker-compose y accediendo por "http://localhost:8888" me sale constantemente el siguiente error:

`
Cannot save template file '../templates/default/cache/index.tpl.it'
`

Creo que no es un error de permisos, he probado ejecutarlo tanto como usuario 1000 como root (y modificando el owner de los ficheros en ambos casos)

No estoy muy seguro de por donde seguir. Alguno idea de que error puedo estar cometiendo? puedo ayudar en cualquier cosa?

Salud y gracias

**Comment by damarte** [comment]
Tienes que dar permisos de escritura a los directorios **templates/default/cache** y **logs/** en tu máquina local.

¿Por curiosidad que versión de Docker y sistema operativo estas usando?

**Comment by Asdespadas** [comment]
Perdona, estoy tardando en responder que me esta dando el mismo error. He visto que esas carpetas no tenían permisos de escritura para grupo, aunque ahora creo que es por el owner/group de los ficheros, puede ser que no sea el mismo que el del dentro del docker? ahora estaba probando a añadir `user: "1000"` a las imagenes de docker. Pero me da otros problemas.
Preferiría no tener que ejecutarlo en root

Ahora estoy probando con un portátil con ubuntu 18, docker 19.03.14 y docker-compose 1.27.4, aunque una vez lo hiciera funcionar mi idea era reinstalar el portátil con un debian 10

Gracias!

**Comment by Asdespadas** [comment]
vale, poniendo permisos 777 en "./templates" me ha funcionado, probablemente tenga que ver con el usuario que ejecuta dentro del docker.
Si puedo aportar algo a este proyecto estaría encantado! de momento me iré quejando de lo que vea.

Gracias

**Comment by Asdespadas** [comment]
En resumen,

Hay que añadir permisos 775 para "./logs" del repositorio sgcommander
Hay que añadir permisos 777 para la carpeta templates de los 2 repositorios
```
chmod 775 -R ./sgcommander/logs
chmod 777 -R ./sgcommander/templates
chmod 777 -R ./homepage/templates
```

Ya estoy jugando, lo de que la cuenta se elimina en 48h si no verifico es cierto?
Muchas gracias y se puede cerrar esta issue

**Comment by damarte** [comment]
La validación de la cuenta por correo está desactivada así que no se elimina a las 48 horas.
