### ISSUE TITLE
Planeta Quatum - error on line 185 at column 80

### ISSUE THREAD

**Issue by Asdespadas** [sgcommander/sgcommander#5]
buenas,

he probado con un par de razas y el planeta "Quatum" (qua8642.jpg) da el siguiente error en el apartado de tropas:

![quantum-error](https://user-images.githubusercontent.com/36451590/101686804-d84f8800-3a69-11eb-9dab-3653c6d00cb3.png)

La unidad que falla es esta:
![quatum-tropa-error](https://user-images.githubusercontent.com/36451590/101687025-2e243000-3a6a-11eb-8ed4-c2cb7570bb71.png)

Si puedo ayudar de alguna manera me dices.
Gracias

**Comment by damarte** [comment]
Ya se ha subido la corrección a los scripts de creación de la base de datos.

Si quieres arreglarlo sin tener que reconstruir el universo con las siguientes consultas bastará:

`
UPDATE `sg1`.`unidad` SET `nombre` = 'Coronel Jack O\'Neil Alternativo' WHERE (`id` = '26');
UPDATE `sg1`.`unidad` SET `nombre` = 'Dr. Rodney Mckay Alternativo' WHERE (`id` = '430');
`
