### ISSUE TITLE
No marca leido los menajes ni funcionan las batallas

### ISSUE THREAD

**Issue by MilorES** [sgcommander/sgcommander#9]
Quería hacer cierto cambios en batallas y mirar de modificar cosilla para nivelar batallas. 
¿Están desactivas? ¿O se rompieron en alguna versión? (Por tirar de una versión antigua) 

Nota: Al fallarme los mensajes lo mismo es algo del servidor :/

Nota: Gracias por compartir el código menuda complejidad!

**Comment by damarte** [comment]
Hola, ¿lo tienes desplegado con docker? ¿puedes poner los logs de los contenedores?

**Comment by MilorES** [comment]
Si, lo tengo desplegado en docker teóricamente con la ultima versión que hay en github.
¿Filtro los logs por algo en particular? (Porque debe haber bastante).

He visto que si los jugadores están en una alianza si que funciona... la primera prueba la hice sin alianza "no recuerdo si a quien atacaba tenía", por lo que he visto hay algo en "issues" de que no funcionan los ataques si estás sin alianza tengo que darle un vistacillo.

Pero de que no se marquen los mensajes como leidos... no vi nada (puede que se me pasara).

Nota: El codigo del fuego rápido es el que no pillo de momento aunque solo le di una mirada :D

**Comment by MilorES** [comment]
El error es: 
`[Jan 15 09:22:01] [/var/www/libs/SPDO.php (line 160)] [error] [code 256] Query Error (1406) Data too long for column 'leido' at row 1----------------------------UPDATE recibeMensaje SET leido='1'  WHERE idMensaje IN ('10745')  AND idJugador='4'`

Así a bote pronto podría ser que se metiendo un STRING/VARCHAR y es un entero.

Me sorprende que si usas este codigo en el servidor de azure no falle.. o es que es otra version?

**Comment by damarte** [comment]
Corregido problema de mensajes en #10
